name = "gleeunit"
version = "0.1.0"
description = "Gleam bindings to the Erlang EUnit test framework"
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = "~> 0.17"

[dev-dependencies]
# some_test_package = "~> 1.0.0"
