name = "gleeunit"
version = "0.5.1"
licences = ["Apache-2.0"]
description = "Gleam bindings to Erlang's EUnit test framework"

[dependencies]
gleam_stdlib = "~> 0.17"

[dev-dependencies]
# some_test_package = "~> 1.0.0"
