name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1.15.1
        with:
          otp-version: "25.1"
          gleam-version: "nightly"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: gleam format --check src test

      - run: gleam test --target erlang
      - run: gleam test --target javascript --runtime node
      - run: gleam test --target javascript --runtime deno
