name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1.13.0
        with:
          otp-version: "25.1"
          gleam-version: "0.25.2"
      - run: gleam format --check src test
      - run: gleam test
      - run: gleam test --target javascript
